### ISSUE TITLE
Connect to DensityInterface

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureBase.jl#28]
We'd like to connect to https://github.com/JuliaMath/DensityInterface.jl

Some notes here about relevant aspects of our approach...

DensityInterface exports a `logdensityof` function that includes a only a two-argument method. MeasureTheory currently has a two-argument _and_ three-argument `logdensity`. We'll very likely (certainly?) need to separate these in order to be compatible.

Given any two of a measure μ, a measure ν, and a density dμ/dν, we can find the third. But the "find the base measure" problem doesn't come up much in practice. So we really have two things we implement

## Density

Given measures `μ` and `base`, we can find the density. This is represented in a `Density` object,
```julia
struct Density{M,B,L}
    μ::M
    base::B
    log::L
end
```
A `Density` can be constructed using `𝒹` or `log𝒹`, depending whether we want the log.

## DensityMeasure

Given a measure `base` and a function `f`, we can use these to build a new measure having `base` as the base measure and `f` as the density (or log-density). This constructs a `DensityMeasure`,
```julia
struct DensityMeasure{F,B,L} <: AbstractMeasure
    f::F
    base::B
    log::L
end
```

This can be constructed using `∫` or `∫exp`, depending whether the function `f` is to be interpreted as a density or log-density.

## Relationship between `Density` and `DensityMeasure` constructions

The above constructions are inverses, in the sense of the tests
```julia
@testset "Density measures and Radon-Nikodym" begin
    x = randn()
    let d = ∫(𝒹(Cauchy(), Normal()), Normal())
        @test logdensity(d, x) ≈ logdensity(Cauchy(), x) 
    end

    let f = 𝒹(∫(x -> x^2, Normal()), Normal())
        @test f(x) ≈ x^2
    end

    let d = ∫exp(log𝒹(Cauchy(), Normal()), Normal())
        @test logdensity(d, x) ≈ logdensity(Cauchy(), x) 
    end

    let f = log𝒹(∫exp(x -> x^2, Normal()), Normal())
        @test f(x) ≈ x^2
    end
end
```

----------------------------

`DensityInterface` takes a different approach to this. `DensityInterface.logdensityof` takes a "density-like" object that can be a measure, a density between two measures, or even something completely different like a likelihood function. 

To fully adopt this will lead to very often having calls that look like "compute the log-density of this log-density". The best way to interpret this seems to be that the first argument is something that _is_ a density, _has_ a density, or is a likelihood.

We'll need to decide how far to buy into this. Some questions:
1. Do we want to add a method for `DensityInterface.logdensityof(::MeasureBase.Density, x)`? `Density` itself will need to change to accomodate this (the `log` field would no longer be needed). The name is a little strange, but there does seem to be some computational convenience
2. Do we want to support `DensityInterface.logdensityof(::MeasureBase.Likelihood, x)`? We currently have something very similar, but to me it was a quick fix; I hadn't considered whether to commit to this as a long-term approach.

-------------------------

Next, we have `DensityInterface.logfuncdensity`. This takes a function and treats it as a log-density. There's no option to specify a base measure. Common use seems to imply this should be over Lebesgue measure, but I don't think there's a way to get the dimensionality. It's not clear to me how this could connect with MeasureTheory.

-------------------------

The question here isn't whether this matches our current approach; it certainly doesn't. More importantly, _**to what extent can we adopt this and still be able to reason about our code?**_

We currently have some laws (the tests above). A good first step might be to think through what laws we can expect to hold using this interface.

**Comment by cscherrer** [comment]
Thinking through this some more, there's some pedagogical danger here. `logdensityof` takes the perspective "everything is a density". But beginners who get used to this might then expect to be able to do things like use a likelihood as a base measure, or find the base measure of a function. These things don't make any sense, and could only lead to an error being thrown or nonsense results. But beginners are unlikely to understand that the problem lies in conflating the concepts in the first place, instead blaming MeasureTheory.

This is a serious concern, and for me it's reason enough to not _fully_ embrace the interface. This leaves us with two options I can see:
1. We add the interface only as a way to connect with packages like BAT and Distributions (not using it much in the code, and not encouraging it in examples), or
2. We have a small package to disambiguate the concepts

There may well be other options beyond this. In any case, the recent DensityInterface sprint seems to have very quickly gotten traction, and it seems unlikely we'll be able to remove any of the current functionality. Next steps aren't at all clear to me.

**Comment by oschulz** [comment]
>```julia
struct Density{M,B,L}
    μ::M
    base::B
    log::L
end
```
>
> A Density can be constructed using 𝒹 or log𝒹, depending whether we want the log.

Why fix log/non-log here, though? The nice thing about DensityInterface is that it leaves the decision regarding log/non-log to the user, not the creator. So it could just be

```julia
struct Density{M,B}
    μ::M
    base::B
end
```

which would support both `densityof` and `logdensityof`. For convenience, we could then define

```
𝒹(μ, base) = Density(μ, base)
```

There would be no need for `log𝒹`, people would just use `logdensityof(𝒹(μ, base))` or `densityof(𝒹(μ, base))` to get an actual log/non-log density function.

Maybe call it `RadonNikodymDerivative` instead of `Density` (which is a bit generic)?


>```julia
struct DensityMeasure{F,B,L} <: AbstractMeasure
    f::F
    base::B
    log::L
end
```
>
>This can be constructed using ∫ or ∫exp, depending whether the function f is to be interpreted as a density or log-density.

Same thing here - we could leave explicit information about log/non-log out there. Instead, it could just be

```julia
struct DensityMeasure{D,B} <: AbstractMeasure
    d::D
    base::B
end
```

with a density `d` that supports DensityInterface. We'd define

```
DensityInterface.logdensityof(m::DensityMeasure, x) = logdensityof(m.d, x)
DensityInterface.logdensityof(m::DensityMeasure) = logdensityof(m.d)
DensityInterface.densityof(m::DensityMeasure, x) = densityof(m.d, x)
DensityInterface.densityof(m::DensityMeasure) = densityof(m.d)
```

For convenience, we could then define something like

```
∫(f, base) = DensityMeasure(hasdensity(f) ? f : funcdensity(f), base)
∫exp(f, base) = DensityMeasure(logfuncdensity(f), base)
```

We'd have to add `funcdensity` (or similar name) to DensityInterface to complement `logfuncdensity` (probably should do that anyway, for symmetry).

I guess an alternative name for `DensityMeasure` would be `RadonNikodymIntegral`?

**Comment by cscherrer** [comment]
> There would be no need for `log𝒹`, people would just use `logdensityof(𝒹(μ, base))` or `densityof(𝒹(μ, base))` to get an actual log/non-log density function.

In terms of dispatch this is really nice. I'm still concerned with the pedagogical side of things, taking "density of a density" is confusing.

> Maybe call it `RadonNikodymDerivative` instead of `Density` (which is a bit generic)?

These are the same thing. My concern with picking a scary-sounding name is that people will think it's a scary thing. 

> Same thing here - we could leave explicit information about log/non-log out there. Instead, it could just be
> 
> ```julia
> struct DensityMeasure{D,B} <: AbstractMeasure
>     d::D
>     base::B
> end
> ```

Just to be clear, `d` here is the density? `d` is a little confusing, since often that's a distribution. 

> I guess an alternative name for `DensityMeasure` would be `RadonNikodymIntegral`?

Yes, but same as above - we'd like to avoid making it sound complicated.

**Comment by oschulz** [comment]
> logdensityof takes the perspective "everything is a density". But beginners who get used to this might then expect to be able to do things like use a likelihood as a base measure, or find the base measure of a function.

I would rather say "everything (compatible with it) *is* or *has* a (natural) density". But it's essentially true, DensityInterface is flexible here on purpose, and I understand your concern. In applications that are written in terms of measure theory, we'd want to defend against such combinations.

We could use a trait `ismeasure` though and define these defaults in DensityInterface:

```julia
ismeasure(object) = false
hasdensity(object) = ismeasure(object)
```

The semantics would be:

* `hasdensity(object) && ismeasure(object)`: `object` is a measure.
* `hasdensity(object) && !ismeasure(object)`: `object` is a density.
* `!hasdensity(object) && !ismeasure(object)`: We don't support you, `object`.
* `!hasdensity(object) && ismeasure(object)`: Nonsense - whoever specialized these for `typeof(object)`, read the docs!

**Comment by phipsgabler** [comment]
> In any case, the recent DensityInterface sprint seems to have very quickly gotten traction, and it seems unlikely we'll be able to remove any of the current functionality.

Well, I don't _really_ have any skin in the game here, but my mid-term goal is to propagate adoption of DensityInterface down to Turing and use it to allow combining models with Soss. So I'd greatly appreciate and will support changes necessary to accomodate MeasureTheory. 

The "traction" until now hasn't gone beyond adding the interface in AbstractPPL and Distributions, so there's still flexibility. I was just enthusiastic to finally get some cross-package effort going, but we definitely should take our time to make everybody happy.

**Comment by oschulz** [comment]
I fully agree DensityInterface it not set in stone. I don't think the behavior of `[log]densityof(obj[, x])` can change or be restricted much (like be restricted to non-measures), since it orginated from a clear need across several inference-related packages. But see my proposal in JuliaMath/DensityInterface.jl#5 regarding possible changes (and those doesn't have to be the limit).

**Comment by cscherrer** [comment]
Thanks @phipsgabler, I appreciate that this is a priority for you. And thank you @oschulz, I can see you're doing a lot of work on this to try to make everyone happy. It means a lot.

**Comment by oschulz** [comment]
You're very welcome, @cscherrer ! After talking to you and @mschauer I feel that there's a lot of potential in wide support for measure theory concepts, especially if there a "soft path" to them and it can be done in a very lightweight way. I'm interested to see where this could go.

**Comment by cscherrer** [comment]
[Replying to @devmotion's comment https://github.com/JuliaMath/DensityInterface.jl/pull/9#issuecomment-967620256]

> In particular, an implementation of densities with implicit base measures is not incorrect, it just does not expose the base measure (which is always present) and hence does not allow to set or query the base measure. In many cases it is completely valid to use an implicit base measure, and most software programs that deal with probability distributions are designed in this way.

I agree. I understand the desire to keep DensityInterface simple and avoid functions to work with base measures. But as you say, the base measure is still there, even if it's not exposed by DensityInterface. This is what I meant by "hiding complexity".

> I think this is the key point: In many cases one can work with probability distributions and densities without diving into measure theory, and hence most users and developers won't and don't have to study measure theory when using DensityInterface (even though it might be useful for them smile). In my opinion, it is absolutely crucial for a widespread adoption of the interface if it allows to deal with densities with respect to implicit base measures.

:+1: 

> > That's our implementation. We call this logdensity because that's exactly what it is. But it clearly conflicts with the expectations of DensityInterface.
> 
> No, it doesn't. It doesn't conflict with my expectations of the interface at all. As I wrote multiple times: DensityInterface assumes that the densities are defined with respect to some, possibly implicit, base measure (since this is the only way to define a density) but it does not assume or enforce the use of specific base measures. In my view, it is completely fine for the interface to define the log density of a normal distribution in the way you did.

@oschulz has pointed out (correctly, I think) that having `logdensityof(Distributions.Normal(), x)` and `logdensityof(MeasureTheory.Normal(), x)` return different things (because a different base measure is used) will be very confusing to new users, and suggested (hope I'm paraphrasing Oliver accurately) that for cases like this `logdensityof` should be with respect to measures like Lebesgue or counting measure.

> As I said, I assume that most implementations will use the Lebesgue or counting measure as base measures but only because these are common choices. It is the users' responsibility to ensure that densities are defined with base measures that they expect and that the computations are correct, i.e., base measures are compatible.
> 
> > We need a way out of this, and I see only two options:
> 
> The main point of MeasureTheory and MeasureBase implementing the DensityInterface would be that measures and densities (with explicltly defined base measure!) can be used in packages that use `logdensityof` for evaluation of log densities. Throughout the DensityInterface API is the responsibility of users to ensure that they obtain the log densities they expect - e.g. by evaluating measures with the desired default base measure or using something like `RadonNikodymDerivative` with explicitly defined base measure.
> 
> In addition to this common basic API MeasureBase would define an additional measure theoretical API - for e.g. `basemeasure`, different base measures such as a Lebesgue measure, counting measure, etc., and something like `RadonNikodymDerivative` that would allow construction and computations with densities with respect to possibly non-default base measures. Densities and distributions that want to participate in the MeasureTheory ecosystem would have to implement this interface and not only DensityInterface.

Right. I think the main tension here is
1. It would be nice for `logdensityof(MeasureTheory.Normal(), x)` to be "user friendly" (as for Distributions.Normal)
2. We currently define log-densities using `MeasureBase.logdensity`, usually with respect to some "non-standard" base measure
3. We'd like our log-densities to still be called that
4. Using `DensityInterface` and `MeasureBase.logdensity` together in their current forms will be very confusing all around

Alternatively to having `logdensityof(MeasureTheory.Normal(), x)` and `logdensityof(Distributions.Normal(), x)` be equivalent, we could just use `logpdf`. But that's badly named for this use, becauase e.g. Lebesgue is not normalizable.

**Comment by oschulz** [comment]
> I agree. I understand the desire to keep DensityInterface simple and avoid functions to work with base measures. But as you say, the base measure is still there, even if it's not exposed by DensityInterface. This is what I meant by "hiding complexity".

Sure, it's always there - the question is, which one. For `DensityInterface.[log]densityof` I think for many measures it should be the one the measure-theory user would choose (without thinking about it in these terms). I think a natural choice would be the primitive measure down the RD-derivative "stack" - so Lebesgue or counting measure in most cases.

For Distributions, the choice of base measure was clear: `DensityInterface.[log]densityof` returning anything different than `[log]pdf` would be *very* surprising to the user. So in `Distributions` the implicit base measure is "whatever [log]pdf uses for that distribution".

I would argue that measure-theory unaware users are served best, if for measures that can essentially be considered to be distributions (but are not necessarily normalized), the behavior of `DensityInterface.[log]densityof` should be the same: The return value should be the (log-)PDF value of the equivalent distribution *times* the norm of the measure. If I understand correctly, this is exactly what `logpdf` currently does in `MeasureBase` (see my other comment at the end of this post).


> > I think this is the key point: In many cases one can work with probability distributions and densities without diving into measure theory, and hence most users and developers won't and don't have to study measure theory when using DensityInterface (even though it might be useful for them smile). In my opinion, it is absolutely crucial for a widespread adoption of the interface if it allows to deal with densities with respect to implicit base measures.

I fully agree!


> DensityInterface [...] does not assume or enforce the use of specific base measures.

Indeed, that is up to the package that defines the measure and the behavior of DensityInterface for them. However I would again argue that users are best served if the base measure is chosen as the average users would typically choose (even if they do so "implicitly", without even realizing that they are).

 
> @oschulz has pointed out (correctly, I think) that having `logdensityof(Distributions.Normal(), x)` and `logdensityof(MeasureTheory.Normal(), x)` return different things (because a different base measure is used) will be very confusing to new users, and suggested (hope I'm paraphrasing Oliver accurately) that for cases like this `logdensityof` should be with respect to measures like Lebesgue or counting measure.

Yes, that's what I meant. I won't always be Lebesque or counting measure, of course - for a Dirichlet(-like) measure I think the best choice would again be what `[log]pdf` uses for `Dirichlet` in Distributions.

I think that at least in many cases, a good choice would be `rootmeasure(m)`.

There will certainly be measures for which choosing Lebesgue or counting would not work - but where they are applicable I would argue that they would be the "natural" (conscious or unconscious) choice of the average user.


> > As I said, I assume that most implementations will use the Lebesgue or counting measure as base measures but only because these are common choices. It is the users' responsibility to ensure that densities are defined with base measures that they expect and that the computations are correct, i.e., base measures are compatible.
> > > We need a way out of this, and I see only two options:

I don't think this can or need to be automatized. But I do think we should have a way to query which base measure DensityInterface will use for a measure. We could call it `defaultbasemeaure(m)` or so. It would *not* be the same as the current `basemeasure` (but possibly very similar or identical to `rootmeasure`).

Also, I don't think `DensityInterface.[log]densityof` absolutely has support every measure: If there is no "obvious" average-user choice of base measure for a measure that's maybe a bit more exotic, we could just say that `defaultbasemeaure(m) == missing`


> 4. Using `DensityInterface` and `MeasureBase.logdensity` together in their current forms will be very confusing all around

I don't think so:

I would argue that to the average user `DensityInterface.logdensityof(m, x)` carries intuitive meaning. I believe for most measures the majority of average users would agree on what it should return.

The same is certainly true for `MeasureBase.logdensity(m, base, x)`: it's rigorously defined what the result should be.

So I'm sure `DensityInterface.logdensityof(m, x)` and `MeasureBase.logdensity(m, base, x)` will play well together.

Then there's `MeasureBase.logdensity(m, x)`. After playing a bit with MeasureTheory I think it's useless (*duck and cover*). Useless to the *user* of `m`, that is, *not useless* to the one implementing `typeof(m)`! That's because using it without looking at `basemeasure(m)` first means it's return value is essentially unpredictable:

```julia
a = ∫exp(log_f, ∫exp(log_f, base))
b = ∫exp(log_f ∘ log_f, base)

logdensity(a, x) != logdensity(a, x)
```

Those two densities are equivalent, mathematically (I would say they are the "same"), but the result of `logdensity` is completely different of course. The two-argument `logdensity` is used to *define* densities in MeasureBase. But it's result depends on the mechanism by which the density was *constructed*, not on what it *semantically represents*. That's why I say it's "useless" to the user.

So to me, `DensityInterface.logdensityof(m, x)` and `MeasureBase.logdensity(m, x)` carry completely different semantics - I would argue that the latter carries no user-facing semantics at all, in fact.

Maybe `MeasureBase.logdensity(m, x)` and `MeasureBase.logdensity(m, base, x)` should not even use the same function name (*duck again*), maybe the first one should be called `MeasureBase.logdensity_impl(m, x)` or so, to make clear that it's a "helper function". ;-)


> Alternatively to having `logdensityof(MeasureTheory.Normal(), x)`
> and `logdensityof(Distributions.Normal(), x)` be equivalent, 

Indeed I don't think the definition of `MeasureTheory.Normal()` should have to change at all! I would rather say they already *are* equivalent - the fact that `MeasureBase.logdensity(m, x)` returns different values for them is irrelevant. Seen as mathematical objects (not looking at the implementation), how could you distinguish them? They have the same norm, give you equally distributed samples and they have the same dν/dμ for any choice of common μ.


> we could just use `logpdf`. But that's badly named for this use, becauase e.g. Lebesgue is not normalizable.


That is exactly what I would propose - replace `logpdf` in MeasureBase by `DensityInterface.logdensityof`. And it's return value should *not* be "auto-normalized" (exactly how `logpdf` in MeasureBase behaves right now, if I'm correct, despite the name).

**Comment by oschulz** [comment]
Close now?

**Comment by cscherrer** [comment]
Oh, right. Thanks for catching this 🙂

**Comment by oschulz** [comment]
;-)
