### ISSUE TITLE
Likelihood docs look outdated

### ISSUE THREAD

**Issue by ptiede** [cscherrer/MeasureBase.jl#36]
Hi I am attempting to use MeasureBase.jl for some of my research, and it looks like the example in the docs is broken. Namely, the following example doesn't seem to work

```julia
  The product on the right side is computed pointwise. To work with this in MeasureBase, we have a "pointwise product" ⊙,
  which takes a measure and a likelihood, and returns a new measure, that is, the unnormalized posterior that has density
  P(θ) P(x|θ) with respect to the base measure of the prior.

  For example, say we have

  μ ~ Normal()
  x ~ Normal(μ,σ)
  σ = 1

  and we observe x=3. We can compute the posterior measure on μ as

  julia> post = Normal() ⊙ Likelihood(Normal{(:μ, :σ)}, (σ=1,), 3)
  Normal() ⊙ Likelihood(Normal{(:μ, :σ), T} where T, (σ = 1,), 3)
  
  julia> logdensity(post, 2)
  -2.5
```

What's the current correct way to use Likelihood?

**Comment by ptiede** [comment]
Ahhh I think I got it! So it looks like the new Likelihood expects a kernel that constructs the appropriate measure. So something like 

```julia
k = kernel(Normal{(:μ, :σ)}, σ=x->1, μ = x->x^2)
lklhd = Likelihood(k, 2.0)
logdensity(lklhd, 1.0) 
```

Seems to work. I really like this approach. It actually makes interfacing my code with MeasureTheory super simple! Let me know if you need any help with the docs. I'd love to help with MeasureTheory, Soss, and any other of your packages!

**Comment by cscherrer** [comment]
Great! I'll have some more changes on the way, for example writing things in terms of exponential families where that's possible, so likelihoods can be very efficient.

Also, the upcoming release will be under the AGPL license. This way I can keep things open, but also have some income from commercial licensing so I can continue to do this work. Docs will be different though, maybe Creative Commons or something, so those won't be affected.

Anyway, yes, I'd welcome any help with docs. Since there are some changes on the way, we should talk before you spend time on it - I'd hate for you to work on writing something only to have it change a few weeks later.

I'll close this now, we can discuss more in a chat or call if you like. Thanks!
